version: '3.8'

services:
  app:
    build: .
    image: game-port-manager:latest
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - ./data:/data
    environment:
      - PORT=3010
    command: uvicorn main:app --host 0.0.0.0 --port 3010
